## Numpy官网学习：http://www.numpy.org/
* (jupyter notebook用法：https://blog.csdn.net/liuyanlin610/article/details/77059848)
* (markdown语法：https://www.cnblogs.com/liugang-vip/p/6337580.html)
* Ctrl + Enter: 执行单元格代码
* Shift + Enter: 执行单元格代码并且移动到下一个单元格
* Alt + Enter: 执行单元格代码，新建并移动到下一个单元格

## 第一章 数组array的构造

### 0.Numpy概述


*    标准安装的Python中用列表(list)保存一组值，可以用来当作数组使用，不过由于列表的元素可以是任何对象，因此列表中所保存的是对象的指针。这样为了保存一个简单的[1,2,3]，需要有3个指针和三个整数对象。对于数值运算来说这种结构显然比较浪费内存和CPU计算时间。
*    NumPy的诞生弥补了这些不足，NumPy提供了两种基本的对象：ndarray（N-dimensional array object）和 ufunc（universal function object）。ndarray(下文统一称之为数组)是存储单一数据类型的多维数组，而ufunc则是能够对数组进行处理的函数,即能够进行向量化运算的内置函数。
*    创建ndarray数组：ndarray是N维数组对象（矩阵），所有元素必须是相同类型。
*    （1）若由列表生成数组，且列表中元素有数字、字符串，则首先会将数字改成字符串，再生成数组，此时数组中的元素均为字符串的统一类型。
*    （2）若a是一个Dataframe,则a.values是一个数组，而且数组中的元素类型可以不一致，这些元素的类型为object,这属于复杂的数组结构类型。

In [1]:
import numpy as np
print(np.__version__)
#help(np.append)  #了解这个函数的详细内容,和下边这行功能一样
np.append?
#shift+tab键的使用：当不知道某一个函数具体使用尤其是函数中的参数是什么时，
#将鼠标放在该函数处，#按shift+tab键一次、两次、三次会逐步现实该函数详细介绍。
#此功能不仅对函数适用，对任何变量也适用。

1.14.0


### 1.tuple和list转成numpy的array数据类型

In [5]:
import numpy as np

#由列表list生成数组array
my_list=[12,23,24,-19]
my_np_array=np.array(my_list)   
#由元组tuple生成数组array
my_tuple=(11,2,3,6,7)    
myt_array=np.array(my_tuple)
#列表、元组的倍数与数组倍数的不同
print(my_list*3)
print(my_tuple*3)
print(np.array(my_tuple)*3)

[12, 23, 24, -19, 12, 23, 24, -19, 12, 23, 24, -19]
(11, 2, 3, 6, 7, 11, 2, 3, 6, 7, 11, 2, 3, 6, 7)
[33  6  9 18 21]


### 2.arange()、linspace()生成数组

In [4]:
import numpy as np
#1.函数arange()
np.arange(9)   #此函数生成数组array，不包括尾数
np.arange(2,9)
print(np.arange(2,9,2))

#2.函数linspace()
print(np.linspace(2,10,10))   #在区间[2,10]均分后生成包括端点的10个点。

#3.关于python中的函数range()的说明(不生成数组)。
range(10)   #是python内置函数，生成一个迭代器，常用于循环遍历
list(range(10))   #将迭代器转换为列表
for i in range(3):  #常用在循环中，此时python2和python3一样使用
    print(i)

[2 4 6 8]
[ 2.          2.88888889  3.77777778  4.66666667  5.55555556  6.44444444
  7.33333333  8.22222222  9.11111111 10.        ]
0
1
2


### 3.元素为1的矩阵ones和元素全为0的矩阵zeros的自动生成

In [8]:
np.zeros(6)   #一维零数组
np.zeros((2,3))  #二维零数组
np.zeros((2,3,4))   #三维零数组

np.ones(5)    #一维数组，元素都是1
np.ones((5,3))   #二维数组，元素都是1

np.ones(5,dtype='int32')   #指定数组元素的数据类型，默认为浮点型。
my_one=np.ones((5,3),dtype='int64')
print(my_one)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


### 4.随机数组的生成

#### (1)生成一个随机数

In [ ]:
import numpy as np
np.random.seed(10)  # random.seed()，省略参数意味着取当前系统时间
np.random.random()  ## 产生一个[0,1)之间的浮点型随机数
#print(np.random.random())  #同一个种子值，产生的随机数相同

#### (2)生成服从均匀分布的随机数组

In [8]:
#1.生成一个一维随机数组（每个数来自于[1,6)上的均匀分布）
import numpy as np
5*np.random.random(10) + 1   #返回一个数组array
np.random.uniform(1, 6, 10)   #同上一行一样的功能
np.random.randint(1, 6, 10)  # 产生每个数来自于均匀分布的整型一维随机数组
#2.生成一个二维随机数组（每个数来自于[1,6)上的均匀分布）
5*np.random.random(size=(3,4))+1  #"size="可以不写
np.random.uniform(1,6,size=(3,4)) 
np.random.randint(1,6,size=(3,4)) 

array([[2, 5, 2, 5],
       [3, 3, 2, 1],
       [2, 4, 3, 1]])

#### (3)生成服正态分布的随机数组

In [11]:
#1.生成标准正态分布随机数组
import numpy as np
np.random.normal(size=(5, 2))  # 产生5x2的每个元素来自标准正态分布的样本矩阵,
#2.生成均值为85，标准差为4的100个正态分布随机数
sampleNo = 100;   #样本个数
mu = 85     #均值
sigma = 4   #标准差
s1 = np.random.normal(mu, sigma, size=sampleNo)  #返回是一维数组
s2 = np.random.normal(mu, sigma, size=(5,2))     #返回是二维数组
print(s2)

[[86.10015173 85.17055065]
 [80.92583901 81.47408163]
 [84.24329411 84.06297727]
 [85.1156306  88.59209579]
 [82.14359052 81.70238365]]


#### (4)生成服从二项分布的随机数组

In [15]:
import numpy as np
#生成来自于n=5，p=0.5的二项分布的样本构成的一维数组。
np.random.binomial(n=5,p=0.5,size=5)
#生成来自于n=5，p=0.5的二项分布的样本构成的二维数组。
np.random.binomial(n=5,p=0.5,size=(3,5))

array([[5, 3, 3, 2, 4],
       [3, 3, 3, 1, 4],
       [1, 2, 2, 4, 4]])

### 5.读入文件构成的数组

In [18]:
#关于文件读写的详细内容在后边章节中
import numpy as np
my_array=np.loadtxt('b.txt',delimiter=',') #无delimiter时默认以空格作为分隔符读入
print(my_array)

[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
