## 第二章 数组属性及形状改变

### 1.数组的重要属性(size、ndim、dtype、shape)

In [ ]:
import numpy as np
my_array=np.array([[1,2,3,4],[5,4,3,6],[3,5,2,7]])
print(my_array.size)   #数组中元素的总个数
print(my_array.ndim)   #数组维度
print(my_array.dtype)  #数组中元素的类型
print(my_array.shape)  #数组的形状
print(my_array.shape[0])   #提取数组行数的方法
print(my_array.shape[1])   #提取数组列数的方法
#以下特别说明python中的len()函数
print(len(my_array1))   #len()函数是python内置函数，返回数组中维度为0方向上的个数

### 2.改变数组形状函数reshape()(浅拷贝)

In [2]:
#注1：reshape()是属于标准的视图浅拷贝
#注2：下边的my_array,my_array1,my_array2,my_array3属于视图浅拷贝，数据一样
#     只是观察的角度不一样，其中一个数组的元素发生变化，其他数组的元素都随之变化。
#     因为这几个数组指向相同的id值，只是观看形状不一样。
import numpy as np
my_array2=my_array1.reshape((4,3))   #my_array1数组不变，但返回一个新的数组
my_array1.shape=(6,2)   #my_array1数组变成了新的数组
my_array=np.arange(6)
#生成6行1列的二维数组,-1代表有几行就是几行，一般用在不知元素个数的时候。
my_array1=my_array.reshape((-1,1)) 
my_array2=my_array.reshape((1,-1))  #生成1行6列的二维数组
my_array3=my_array.reshape((2,3)) #生成2行3列的二维数组，my_array没有变，浅拷贝。

### 3.改变数组形状函数ravel()、属性flat（浅拷贝）

In [3]:
#ravel()属于标准的视图浅拷贝
import numpy as np
my_array=np.arange(12).reshape((3,4))   #二维数组
my_ravel=my_array.ravel() #返回一维数组
my_flat=my_array.flat   #flat是属性，返回一个迭代器，用于遍历。

### 4.数组转置函数transpose()（浅拷贝）

In [1]:
#此处也是视图浅拷贝，改变一个数组中元素的值，其他数组的的元素做相应改变。
import numpy as np
my_array=np.arange(15).reshape((3,5))
my_tr_array1=np.transpose(my_array)   #转置函数，也可以用下边数组的方法完成转置。
my_tr_array2=my_array.T               #也可以用数组的方法实行转置
print(my_array)
print()
print(my_tr_array1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
