## 第四章、数组拷贝、合并、分离、删除

### 1.数组视图、浅拷贝、深拷贝

In [1]:
import numpy as np
my_array=np.array([20,30,12,13,14,76])
my_array1=my_array.view()  #视图，也是浅拷贝
my_array2=my_array         #浅拷贝
my_array3=np.copy(my_array)  #深拷贝
my_array4=my_array.copy()    #深拷贝,同上一行功能一样
my_array[0]=1000
print(my_array)
print(my_array1)
print(my_array2)
print(my_array3)
#注：a=4,b=a,a=5,此时b不变，也就是对于单个变量，这儿“=”是深拷贝，
#但对于列表和数组“=”是浅拷贝

[1000   30   12   13   14   76]
[1000   30   12   13   14   76]
[1000   30   12   13   14   76]
[20 30 12 13 14 76]


### 2.二维数组合并函数hstck()、vstack(),分离函数hsplit()、vsplit()（最常用）（合并深拷贝，分离浅拷贝）

* #### 二维数组合并、分离时用这四个函数方便。

#### (1)合并(深拷贝)

In [31]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.hstack((a,b))   #横着拼成一个2行4列矩阵
print(c)
d=np.vstack((a,b))    #竖着拼成一个4行2列矩阵
print(d)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
新内容
[[100   2]
 [  3   4]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### 2.切分(浅拷贝view)

In [34]:
my_array=np.arange(36).reshape((4,9))
#np.hsplit(my_array,3)返回的是一个列表,每个元素是一个数组array
my_h1=np.hsplit(my_array,3)  #横着水平方向平均分成3份  
my_n=my_h1[0] # my_h1[0]是第0个数组，my_h1[1]是第1个数组。也可按下边方法提取数组。
my_e,my_f,my_g=np.hsplit(my_array,3)       #将my_array按照横着方向平均切分成3份。
my_h,my_m=np.vsplit(my_array,2)         #将my_array按照竖着方向切分成2份
my_e,my_f,my_g=np.hsplit(my_array,[3,7])  #在指定位置切分
print(my_e)
print(my_f)
print(my_g)

[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]
 [27 28 29]]
[[ 3  4  5  6]
 [12 13 14 15]
 [21 22 23 24]
 [30 31 32 33]]
[[ 7  8]
 [16 17]
 [25 26]
 [34 35]]
xin neirong
[[300   1   2   3   4   5   6   7   8]
 [  9  10  11  12  13  14  15  16  17]
 [ 18  19  20  21  22  23  24  25  26]
 [ 27  28  29  30  31  32  33  34  35]]
[[300   1   2]
 [  9  10  11]
 [ 18  19  20]
 [ 27  28  29]]
[[ 3  4  5  6]
 [12 13 14 15]
 [21 22 23 24]
 [30 31 32 33]]
[[ 7  8]
 [16 17]
 [25 26]
 [34 35]]


### 3.数据删除函数delete()（深拷贝）
* ####  (由于生成新的数据，因此是深拷贝)

* #### 二维数组删除函数（删除整行整列）

In [39]:
#不能删除某一个元素，因为删除掉这个元素数组就不是数组了，只能整行整列删除。
import numpy as np
my_array=np.arange(24).reshape((4,6))
my_array1=np.delete(my_array,1,axis=0)  #删除第一行
my_array2=np.delete(my_array,2,axis=1)  #删除第2列
print(my_array)
print()
print(my_array1)
print()
print(my_array2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[ 0  1  3  4  5]
 [ 6  7  9 10 11]
 [12 13 15 16 17]
 [18 19 21 22 23]]
xin neirong
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[100   1   2   3   4   5]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]

[[ 0  1  3  4  5]
 [ 6  7  9 10 11]
 [12 13 15 16 17]
 [18 19 21 22 23]]
